'''
Builds the Speed Rush cars (lowpoly.py + lp_arch.py + cars_lp/roster.py), renders previews and
exports them into the game. Headless:

  blender -b --factory-startup -P lp_build.py -- <id ...|all> [--render] [--export] [--views=rear34,front34]

--render : preview sheet -> out/preview/<id>.png
--export : out/<id>.json (lp2 record), then rewrites js/car-models.js from every out/<id>.json of
           the roster, and the car's side / rear blocks in js/data.js (2D fallback)
'''
import bpy, os, sys, json

BASE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BASE, 'out')
JS = os.path.normpath(os.path.join(BASE, '..', 'js'))


def load_common():
    G = {'__name__': 'lp_build', 'BASE': BASE}
    for f in ('lp_export.py', 'lp_preview.py', 'lowpoly.py', 'lp_arch.py', os.path.join('cars_lp', 'roster.py')):
        p = os.path.join(BASE, f)
        exec(compile(open(p, encoding='utf-8').read(), p, 'exec'), G)
    return G


def write_models(G):
    '''js/car-models.js from out/<id>.json, in roster (slot) order.'''
    lines = ["'use strict';", '/* Speed Rush car models (lp2). Generated by blender/lp_build.py: do not edit. */',
             'window.TG = window.TG || {};', 'TG.CarModels = {', '  fmt: "lp2",', '  mats: ' + json.dumps(G['GAME_MATS']) + ',', '  cars: {']
    n = 0
    for c in G['CARS']:
        p = os.path.join(OUT, c['d']['id'] + '.json')
        if not os.path.exists(p):
            continue
        rec = json.load(open(p))
        lines.append('    ' + json.dumps(c['d']['id']) + ': {meta: ' + json.dumps(rec['meta'], separators=(',', ':')) + ', z: ' + json.dumps(rec['z']) + '},')
        n += 1
    lines += ['  },', '};', '']
    open(os.path.join(JS, 'car-models.js'), 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
    return n


def patch_block(src, cid, key, value):
    '''Replaces `key: {...}` inside the car entry `id: '<cid>'` of data.js.'''
    s = src.index(key + ': {', src.index("id: '%s'" % cid))
    depth, j = 0, s + len(key) + 2
    while True:
        depth += (src[j] == '{') - (src[j] == '}')
        j += 1
        if depth == 0:
            break
    return src[:s] + key + ': ' + json.dumps(value, separators=(', ', ': ')) + src[j:]


def main():
    argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
    views = next((a.split('=', 1)[1] for a in argv if a.startswith('--views=')), 'rear34,front34').split(',')
    G = load_common()
    ids = [a for a in argv if not a.startswith('--')]
    if ids == ['all']:
        ids = [c['d']['id'] for c in G['CARS']]
    data_path = os.path.join(JS, 'data.js')
    for cid in ids:
        S = G['spec'](cid)
        G['build_lowpoly'](S)
        stats = dict(id=cid, faces=len(bpy.data.objects[cid].data.polygons))
        if '--render' in argv:
            os.makedirs(os.path.join(OUT, 'preview'), exist_ok=True)
            stats['sheet'] = os.path.basename(G['render_views'](S, os.path.join(OUT, 'preview', cid), views))
        if '--export' in argv:
            stats['export'] = G['export_car'](S, OUT)
            src = open(data_path, encoding='utf-8').read()
            src = patch_block(src, cid, 'side', G['side_outline'](S))
            src = patch_block(src, cid, 'rear', G['rear_panel'](S))
            open(data_path, 'w', encoding='utf-8', newline='\n').write(src)
        print('LP_BUILD', json.dumps(stats), flush=True)
        # free the car before the next one (a whole roster in one session otherwise runs out of memory)
        coll = bpy.data.collections.get('car_' + cid)
        for ob in list(coll.objects):
            bpy.data.objects.remove(ob)
        bpy.data.collections.remove(coll)
        for me in [m for m in bpy.data.meshes if m.users == 0]:
            bpy.data.meshes.remove(me)
    if '--export' in argv:
        print('LP_MODELS', write_models(G), flush=True)


main()
